language: rust
rust:
  - 1.8.0
  - stable
  - nightly
cache: cargo
sudo: false
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
    - CARGO_INCREMENTAL=0  # decrease size of `target` to make the cache smaller
  matrix:
    - FEATURES=""  # default configuration
    - FEATURES="--no-default-features"
script:
  - cargo test --all $FEATURES --all-targets
notifications:
  email:
    on_success: never
